### ISSUE TITLE
set_gpus function

### ISSUE THREAD

**Issue by haruishi43** [analysiscenter/nbtools#4]
Great tool!

I wanted to use the `set_gpus` function in the README, but it seems that it is not in the `nbtools` library.
Do you plan to opensource it as well?

On a side note, I would like to get this working for vscode and was wondering if you already had ideas for implementing this feature.

**Comment by roman-kh** [comment]
Hi, haruishi43
Thanks for your comment.
`set_gpus` is a part of [batchflow](https://github.com/analysiscenter/batchflow) now. Please, use it freely as it is open-source as well. (`from batchflow import set_gpus`)
We will fix `nbtools` soon.

**Comment by haruishi43** [comment]
I see! thanks for letting me know 👍🏼
